spring:
  datasource:
    url: jdbc:h2:mem:my_mall;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: root
    password: 314500
    driver-class-name: org.h2.Driver
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      # data-locations: classpath:data.sql (å·²åˆ é™¤ï¼Œé˜²æ­¢æŠ¥é”™)

  mail:
    host: smtp.qq.com
    username: 949147765@qq.com
    password: jwzctthvoxtebccd
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

mybatis-plus:
  configuration:
    # ğŸ‘‡ å†æ¬¡ç¡®ä¿å¼€å¯é©¼å³°æ˜ å°„
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl